# Goal of this notebook is to train a neural network model to learn how to do basic addition with two numbers.

In [0]:
import numpy as np
import random

## Generate 3000 number pairs for calculation alongside the expected number after doing addition

In [0]:
Y = np.random.randint(2, 50, size=3000)

In [90]:
Y.shape

(3000,)

In [0]:
X = []
for i in range(Y.shape[0]):
  random_first_number = np.random.randint(1, Y[i])
  random_second_number = Y[i] - random_first_number
  X.append([random_first_number, random_second_number])
 

In [0]:
X = np.asarray(X)

In [93]:
X[0:5]

array([[ 2,  2],
       [ 5, 17],
       [ 4, 36],
       [41,  1],
       [ 8, 20]])

In [94]:
Y[0:5]

array([ 4, 22, 40, 42, 28])

# Import tensorflow dependencies + build model + declare hyperparameters

In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [0]:
def build_model():
  model = keras.Sequential([
      layers.Dense(1, input_shape=(2,))
  ])
  optimizer = keras.optimizers.RMSprop(0.0001)
  model.compile(loss='mean_squared_error',
                optimizer=optimizer,
                metrics=['mean_absolute_error', 'mean_squared_error'])
  return model

In [0]:
model = build_model()


# Start to train model

In [55]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [73]:
history = model.fit(
  X, Y,
  epochs=100,
  validation_split=0.2,
  verbose=1
)

Train on 2400 samples, validate on 600 samples
Epoch 1/100
2400/2400 [==============================] - 0s 77us/sample - loss: 2.3685e-06 - mean_absolute_error: 0.0011 - mean_squared_error: 2.3685e-06 - val_loss: 1.0352e-06 - val_mean_absolute_error: 8.6665e-04 - val_mean_squared_error: 1.0352e-06
Epoch 2/100
2400/2400 [==============================] - 0s 74us/sample - loss: 2.0704e-06 - mean_absolute_error: 0.0011 - mean_squared_error: 2.0704e-06 - val_loss: 6.2388e-06 - val_mean_absolute_error: 0.0022 - val_mean_squared_error: 6.2388e-06
Epoch 3/100
2400/2400 [==============================] - 0s 73us/sample - loss: 2.1779e-06 - mean_absolute_error: 8.5784e-04 - mean_squared_error: 2.1779e-06 - val_loss: 1.4130e-06 - val_mean_absolute_error: 9.6858e-04 - val_mean_squared_error: 1.4130e-06
Epoch 4/100
2400/2400 [==============================] - 0s 72us/sample - loss: 2.1019e-06 - mean_absolute_error: 0.0012 - mean_squared_error: 2.1019e-06 - val_loss: 1.9243e-06 - val_mean_absolute_

# Generate some hard-coded test data to test whether the model is able to perform an addition on two numbers.

In [0]:
X_test = np.asarray([
    [40, 35],
    [100, 30],
    [300, 25],
    [500, 305],
    [200, 301],
    [23, 53]
])

In [99]:
pred_list = model.predict(X_test, verbose=1)

6/6 [==============================] - 0s 405us/sample


In [100]:
pred_list

array([[ 75.006424],
       [130.01118 ],
       [325.028   ],
       [805.0683  ],
       [501.04208 ],
       [ 76.00644 ]], dtype=float32)

In [0]:
stacked_list = np.column_stack((X_test, pred_list))

In [102]:
stacked_list

array([[ 40.        ,  35.        ,  75.00642395],
       [100.        ,  30.        , 130.01118469],
       [300.        ,  25.        , 325.02801514],
       [500.        , 305.        , 805.06829834],
       [200.        , 301.        , 501.04208374],
       [ 23.        ,  53.        ,  76.00643921]])

In [103]:
stacked_list.shape

(6, 3)

In [105]:
for i in range(stacked_list.shape[0]):
  # Round to the nearest number as the predictions gives us decimal points
  print("%d + %d = %d" % (stacked_list[i][0], stacked_list[i][1], round(stacked_list[i][2])))

40 + 35 = 75
100 + 30 = 130
300 + 25 = 325
500 + 305 = 805
200 + 301 = 501
23 + 53 = 76


# Guess we are done!